sudo: required
services:
  - docker

before_install:
  - docker build -t cyw233/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cyw233/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "cyw-docker"
  env: "CywDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-224567944293"
  bucket_path: "cyw-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"